use std::{marker::PhantomData, process::Output};

use futures::StreamExt;
use google_gmail1::api::{
    History, HistoryLabelAdded, HistoryLabelRemoved, HistoryMessageAdded, HistoryMessageDeleted,
};
use log::{error, info};
use serde::{Deserialize, Serialize};
use specta::Type;
use sqlx::{Connection, Executor, Sqlite, Transaction};

use crate::{email::gmail::GmailError, AppError, DbPool};

// todo: use typestate and enum to model account types
#[derive(Debug, Clone)]
pub struct EmailAccount {
    pub id: i64,
    pub email: String,
    pub account_name: String,
    pub config: AccountConfig,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[non_exhaustive]
pub enum AccountConfig {
    // From google_gmail1::api::Profile
    Gmail {
        history_id: HistoryID,
        scopes: Vec<String>,
    },
}

// Contains the history ID and status for a Gmail account.
// When the history ID status is `KnownStale` or an incremental sync returns 404,
// a full sync needs to be performed
#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum HistoryID {
    // TODO change back ot u64
    LastSynced(String),
    KnownStale,
}

pub async fn get_accounts<'a, E>(executor: &'a E) -> Result<Vec<EmailAccount>, crate::AppError>
where
    &'a E: Executor<'a, Database = Sqlite>,
{
    let res = sqlx::query!("SELECT * FROM email_accounts")
        .fetch_all(executor)
        .await
        .map_err(|e| {
            error!("in get_accounts: db returned error {e:?}");
            crate::AppError::Sqlx(e.into())
        })
        .map(|row| {
            row.iter()
                .map(|it| {
                    Ok(EmailAccount {
                        id: it.id,
                        email: it.email.clone(),
                        account_name: it.account_name.clone(),
                        config: serde_json::from_str(&it.account_config).map_err(|e| {
                            error!("while parsing account config: {e:?}");
                            crate::AppError::from(e)
                        })?,
                    })
                })
                // discard invalid rows
                // TODO: delete invalid rows
                .filter_map(|e: Result<EmailAccount, crate::AppError>| {
                    if let Err(e) = &e {
                        error!("failed to parse account row due to {e:?}");
                    }
                    e.ok()
                })
                .collect::<Vec<EmailAccount>>()
        });

    res
}

/// Insert a new `account` into the database.
/// `EmailAccount::id` is ignored and will be generated by the database.
/// Returns the generated `id`.
pub async fn add_account<'a, E>(
    executor: &'a E,
    account: EmailAccount,
) -> Result<i64, crate::AppError>
where
    &'a E: Executor<'a, Database = Sqlite>,
{
    // TODO: this overwrites the account config if it already exists
    let account_config_json = serde_json::to_string(&account.config).unwrap();
    sqlx::query!(
        r#"
        INSERT INTO email_accounts (email, account_name, account_config)
        VALUES ($1, $2, $3)
        ON CONFLICT(email) DO UPDATE SET
            account_name = excluded.account_name,
            account_config = excluded.account_config
        RETURNING id
        "#,
        account.email,
        account.account_name,
        account_config_json
    )
    .fetch_one(executor)
    .await
    .map(|res| res.id)
    .map_err(|e| {
        error!("in add_account: db returned error {e:?}");
        crate::AppError::Sqlx(e.into())
    })
}

// https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.labels#Label
pub struct Label {
    pub id: String,
    pub name: String,
    pub message_list_visibility: Option<String>,
    pub label_list_visibility: Option<String>,
    pub type_: String,
}

pub enum AddLabelStatus {
    Inserted,
    AlreadyExists,
}

#[derive(Debug, Clone, Copy, Type, Serialize)]
pub enum MissingField {
    ThreadId,
    SyncCursor,
    LabelIds,
    InternalDate,
    SizeEstimate,
    DateHeader,
    FromAddr,
    ToAddrs,
    CcAddrs,
    InReplyTo,
    MsgReferences,
    Subject,
    Snippet,

    MsgId,
    Payload,
    Headers,
    InLabel,
}

impl From<MissingField> for AppError {
    fn from(f: MissingField) -> Self {
        GmailError::MissingField(f).into()
    }
}

#[derive(sqlx::FromRow)]
pub struct MessageContents {
    pub provider_msg_id: String,
    pub mime_type: String,
    // TODO: convert to &str?
    pub body: String,
}

pub struct MessageSkeleton {
    pub provider_msg_id: String,
    /// Wether the message was previously cached
    /// => only the label ids can change on refetch
    pub previously_cached: bool,
}

// each field is a message since they are
// technically nullable in the DB
pub struct Message {
    pub provider_msg_id: Option<String>,
    pub contents: Vec<MessageContents>,
    pub label_ids: Vec<String>,
    pub size_estimate: Option<i32>,

    // headers:
    // this is the gmail history id
    pub thread_id: Option<String>,
    pub sync_cursor: Option<String>,
    pub internal_date: Option<i64>,
    pub date_header: Option<String>,
    pub from_addr: Option<String>,
    pub to_addrs: Option<String>,
    pub cc_addrs: Option<String>,
    pub subject: Option<String>,
    pub snippet: Option<String>,
}
