use std::marker::PhantomData;

use log::{error, info};
use serde::{Deserialize, Serialize};
use sqlx::{prelude::FromRow, Database, Executor, Sqlite};

// todo: use typestate and enum to model account types
#[derive(Debug, Clone)]
pub struct EmailAccount {
    pub id: i64,
    pub email: String,
    pub account_name: String,
    pub config: AccountConfig,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum AccountConfig {
    // From google_gmail1::api::Profile
    Gmail {
        history_id: HistoryID,
        scopes: Vec<String>,
    },
    // Imap {},
}

// Contains the history ID and status for a Gmail account.
// When the history ID status is `KnownStale` or an incremental sync returns 404,
// a full sync needs to be performed
#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum HistoryID {
    LastSynced(u64),
    KnownStale,
}

pub async fn get_accounts<'a, E>(executor: &'a E) -> Result<Vec<EmailAccount>, crate::AppError>
where
    &'a E: Executor<'a, Database = Sqlite>,
{
    let res = sqlx::query!("SELECT * FROM email_accounts")
        .fetch_all(executor)
        .await
        .map_err(|e| {
            error!("in get_accounts: db returned error {e:?}");
            crate::AppError::SQLXError
        })
        .map(|row| {
            row.iter()
                .map(|it| {
                    Ok(EmailAccount {
                        id: it.id,
                        email: it.email.clone(),
                        account_name: it.account_name.clone(),
                        config: serde_json::from_str(&it.account_config).map_err(|e| {
                            error!("while parsing account config: {e:?}");
                            crate::AppError::SerdeJson
                        })?,
                    })
                })
                // discard invalid rows
                // TODO: delete invalid rows
                .filter_map(|e: Result<EmailAccount, crate::AppError>| {
                    error!("failed to parse: {row:?}\ndue to {e:?}");
                    e.ok()
                })
                .collect::<Vec<EmailAccount>>()
        });

    res
}

/// Insert a new `account` into the database.
/// `EmailAccount::id` is ignored and will be generated by the database.
/// Returns the generated `id`.
pub async fn add_account<'a, E>(executor: &'a E, account: EmailAccount) -> Result<i64, crate::AppError>
where
    &'a E: Executor<'a, Database = Sqlite>,
{
    // TODO: this overwrites the account config if it already exists
    let account_config_json = serde_json::to_string(&account.config).unwrap();
    sqlx::query!(
        r#"
        INSERT INTO email_accounts (email, account_name, account_config)
        VALUES ($1, $2, $3)
        ON CONFLICT(email) DO UPDATE SET
            account_name = excluded.account_name,
            account_config = excluded.account_config
        RETURNING id
        "#,
        account.email,
        account.account_name,
        account_config_json
    )
    .fetch_one(executor)
    .await
    .map(|res| res.id)
    .map_err(|e| {
        error!("in add_account: db returned error {e:?}");
        crate::AppError::SQLXError
    })
}

// https://developers.google.com/workspace/gmail/api/reference/rest/v1/users.labels#Label
pub struct Label {
    pub id: String,
    pub name: String,
    pub message_list_visibility: Option<String>,
    pub label_list_visibility: Option<String>,
    pub type_: String,
}

pub enum AddLabelStatus {
    Inserted,
    AlreadyExists,
}

pub async fn add_label<'a, E>(executor: &'a E, label: Label) -> Result<AddLabelStatus, crate::AppError>
where
    &'a E: Executor<'a, Database = Sqlite>,
{
    sqlx::query!(
        "INSERT INTO labels (id, name, message_list_visibility, label_list_visibility, type)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT (id) DO NOTHING

        ",
        label.id,
        label.name,
        label.message_list_visibility,
        label.label_list_visibility,
        label.type_
    )
    .execute(executor)
    .await
    .map(|r| match r.rows_affected() {
        0 => AddLabelStatus::AlreadyExists,
        1 => AddLabelStatus::Inserted,
        _ => unreachable!(),
    })
    .map_err(|e| {
        error!("in add_label: db returned error {e:?}");
        crate::AppError::SQLXError
    })
}
