// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  register a new gmail account with the oauth2 onboarding flow */
	registerGmailAccount: () => typedError<null, AppError>(__TAURI_INVOKE("register_gmail_account")),
	/**  list all email accounts registered with the application */
	emailListAccounts: () => typedError<ListEmailEntry[], AppError>(__TAURI_INVOKE("email_list_accounts")),
	/**
	 *  Syncs the email account with the given ID
	 * 
	 *  ### Arguments
	 *  - `account_id`: The ID of the account to sync, a u64 serialized as a String
	 */
	devEmailFullSync: (accountId: string) => typedError<null, AppError>(__TAURI_INVOKE("dev_email_full_sync", { accountId })),
	emailSync: (accountId: string) => typedError<null, AppError>(__TAURI_INVOKE("email_sync", { accountId })),
};

/* Types */
export type AppError = "MissingDbPath" | "GmailResponseIncomplete" | "OAuth" | ({ HttpErr: number }) & { GmailApiErr?: never; GmailErr?: never; Sqlx?: never } | ({ Sqlx: SqlxError }) & { GmailApiErr?: never; GmailErr?: never; HttpErr?: never } | "IOError" | "UrlParseError" | "KeyringSaveError" | "KeyringLoadError" | "AccountTypeMismatch" | "GmailMissingLabels" | "SerdeJson" | "AccountNotFound" | ({ GmailErr: GmailError }) & { GmailApiErr?: never; HttpErr?: never; Sqlx?: never } | ({ GmailApiErr: GmailApiError }) & { GmailErr?: never; HttpErr?: never; Sqlx?: never } | "ParseAccountID" | "ParseSyncCursor" | "InvalidEmailBody";

export type GmailApiError = "HttpError" | ({ UploadSizeLimitExceeded: {
	resource_size: number | null,
	max_size: number | null,
} }) & { Failure?: never } | "BadRequest" | "MissingAPIKey" | "MissingToken" | "Cancelled" | "FieldClash" | "JsonDecodeError" | ({ Failure: number }) & { UploadSizeLimitExceeded?: never } | "Io";

export type GmailError = "AuthUrlParse" | "TokenUrlParse" | "RedirectUrlParse" | "OauthRedirect" | "OauthHttpResp" | "OauthTcpListen" | "MessageNotSkeleton" | "UnsupportedMimeVer" | "UnsupportedMimeType" | "MessagePartNotLeaf" | { MissingField: MissingField };

export type ListEmailEntry = {
	id: string,
	name: string,
};

export type MissingField = "ThreadId" | "SyncCursor" | "LabelIds" | "InternalDate" | "SizeEstimate" | "DateHeader" | "FromAddr" | "ToAddrs" | "CcAddrs" | "InReplyTo" | "MsgReferences" | "Subject" | "Snippet" | "MsgId" | "Payload" | "Headers" | "InLabel";

/**  Machine-readable database constraint kind, mirrors `sqlx::error::ErrorKind`. */
export type SqlxDbErrorKind = "UniqueViolation" | "ForeignKeyViolation" | "NotNullViolation" | "CheckViolation" | "Other";

/**
 *  Typed wrapper around `sqlx::Error` with machine-readable variants.
 *  No string fields — use the error `Display` for human messages.
 */
export type SqlxError = "RowNotFound" | 
/**  Database-level error; `kind` encodes the constraint violation category. */
({ Database: {
	kind: SqlxDbErrorKind,
} }) & { ColumnIndexOutOfBounds?: never } | ({ ColumnIndexOutOfBounds: {
	index: number,
	len: number,
} }) & { Database?: never } | "PoolTimedOut" | "PoolClosed" | "WorkerCrashed" | "Other";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

