// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  register a new gmail account with the oauth2 onboarding flow */
	registerGmailAccount: () => typedError<null, AppError>(__TAURI_INVOKE("register_gmail_account")),
	/**  list all email accounts registered with the application */
	emailListAccounts: () => typedError<ListEmailEntry[], AppError>(__TAURI_INVOKE("email_list_accounts")),
	/**
	 *  Syncs the email account with the given ID
	 * 
	 *  ### Arguments
	 *  - `account_id`: The ID of the account to sync, a u64 serialized as a String
	 */
	devEmailFullSync: (accountId: string) => typedError<null, AppError>(__TAURI_INVOKE("dev_email_full_sync", { accountId })),
};

/* Types */
export type AppError = "MissingDbPath" | "GmailResponseIncomplete" | "OAuth" | ({ HttpErr: number }) & { GmailErr?: never } | "SQLXError" | "IOError" | "UrlParseError" | "KeyringSaveError" | "KeyringLoadError" | "AccountTypeMismatch" | "GmailMissingLabels" | "SerdeJson" | ({ GmailErr: GmailError }) & { HttpErr?: never } | "ParseAccountID";

export type GmailError = "AuthUrlParse" | "TokenUrlParse" | "RedirectUrlParse" | "ListLabels" | "GetMessage" | "ListMessages" | "GetProfile" | "OauthRedirect" | "OauthHttpResp" | "OauthTcpListen";

export type ListEmailEntry = {
	id: string,
	name: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

