// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  register a new gmail account with the oauth2 onboarding flow */
	registerGmailAccount: () => typedError<null, AppError>(__TAURI_INVOKE("register_gmail_account")),
	/**  list all email accounts registered with the application */
	emailListAccounts: () => typedError<ListEmailEntry[], AppError>(__TAURI_INVOKE("email_list_accounts")),
	/**
	 *  Syncs the email account with the given ID
	 * 
	 *  ### Arguments
	 *  - `account_id`: The ID of the account to sync, a u64 serialized as a String
	 */
	devEmailFullSync: (accountId: string, updateChannel: Channel<Progress>) => typedError<null, AppError>(__TAURI_INVOKE("dev_email_full_sync", { accountId, updateChannel })),
	emailSync: (accountId: string, updateChannel: Channel<Progress>) => typedError<null, AppError>(__TAURI_INVOKE("email_sync", { accountId, updateChannel })),
	/**  return a list of message stubs */
	listMessages: (accountId: string, mailbox: MailBox, pageIndex: number) => typedError<ListMessages, AppError>(__TAURI_INVOKE("list_messages", { accountId, mailbox, pageIndex })),
};

/* Types */
export type AppError = "MissingDbPath" | "GmailResponseIncomplete" | "OAuth" | ({ HttpErr: number }) & { GmailApiErr?: never; GmailErr?: never; Io?: never; Serde?: never; Sqlx?: never; Tauri?: never } | ({ Sqlx: SqlxError }) & { GmailApiErr?: never; GmailErr?: never; HttpErr?: never; Io?: never; Serde?: never; Tauri?: never } | ({ Io: IoError }) & { GmailApiErr?: never; GmailErr?: never; HttpErr?: never; Serde?: never; Sqlx?: never; Tauri?: never } | "UrlParseError" | "KeyringSaveError" | "KeyringLoadError" | "AccountTypeMismatch" | "GmailMissingLabels" | ({ Serde: SerdeError }) & { GmailApiErr?: never; GmailErr?: never; HttpErr?: never; Io?: never; Sqlx?: never; Tauri?: never } | ({ Tauri: TauriError }) & { GmailApiErr?: never; GmailErr?: never; HttpErr?: never; Io?: never; Serde?: never; Sqlx?: never } | "AccountNotFound" | ({ GmailErr: GmailError }) & { GmailApiErr?: never; HttpErr?: never; Io?: never; Serde?: never; Sqlx?: never; Tauri?: never } | ({ GmailApiErr: GmailApiError }) & { GmailErr?: never; HttpErr?: never; Io?: never; Serde?: never; Sqlx?: never; Tauri?: never } | "ParseAccountID" | "ParseSyncCursor" | "InvalidEmailBody";

export type GmailApiError = "HttpError" | ({ UploadSizeLimitExceeded: {
	resource_size: number | null,
	max_size: number | null,
} }) & { Failure?: never } | "BadRequest" | "MissingAPIKey" | "MissingToken" | "Cancelled" | "FieldClash" | "JsonDecodeError" | ({ Failure: number }) & { UploadSizeLimitExceeded?: never } | "Io";

export type GmailError = "AuthUrlParse" | "TokenUrlParse" | "RedirectUrlParse" | "OauthRedirect" | "OauthHttpResp" | "OauthTcpListen" | "MessageNotSkeleton" | "UnsupportedMimeVer" | "UnsupportedMimeType" | "MessagePartNotLeaf" | { MissingField: MissingField };

/**  Machine-readable subset of `std::io::ErrorKind`; rest collapse to `Other`. */
export type IoError = "NotFound" | "PermissionDenied" | "AlreadyExists" | "Connection" | "TimedOut" | "UnexpectedEof" | "Other";

export type ListEmailEntry = {
	id: string,
	name: string,
};

export type ListMessages = {
	messages: Message[],
	next_page_param: number | null,
};

export type MailBox = "INBOX" | "SENT" | "DRAFT" | "STARRED" | "TRASH" | "SPAM";

export type Message = {
	provider_msg_id: string | null,
	contents: MessageContents[],
	label_ids: string[],
	size_estimate: number | null,
	thread_id: string | null,
	sync_cursor: string | null,
	internal_date: string,
	date_header: string | null,
	from_addr: string | null,
	to_addrs: string | null,
	cc_addrs: string | null,
	subject: string | null,
	snippet: string | null,
};

export type MessageContents = {
	provider_msg_id: string,
	mime_type: string,
	body: string,
};

export type MissingField = "ThreadId" | "SyncCursor" | "LabelIds" | "InternalDate" | "SizeEstimate" | "DateHeader" | "FromAddr" | "ToAddrs" | "CcAddrs" | "InReplyTo" | "MsgReferences" | "Subject" | "Snippet" | "MsgId" | "Payload" | "Headers" | "InLabel";

export type Progress = ({ Update: {
	completed: number,
	out_of: number,
} }) & { Message?: never } | ({ Message: string }) & { Update?: never };

/**  Mirrors `serde_json::error::Category` — the meaningful failure kinds. */
export type SerdeError = "Io" | "Syntax" | "Data" | "Eof";

/**  Machine-readable database constraint kind, mirrors `sqlx::error::ErrorKind`. */
export type SqlxDbErrorKind = "UniqueViolation" | "ForeignKeyViolation" | "NotNullViolation" | "CheckViolation" | "Other";

/**
 *  Typed wrapper around `sqlx::Error` with machine-readable variants.
 *  No string fields — use the error `Display` for human messages.
 */
export type SqlxError = "RowNotFound" | 
/**  Database-level error; `kind` encodes the constraint violation category. */
({ Database: {
	kind: SqlxDbErrorKind,
} }) & { ColumnIndexOutOfBounds?: never } | ({ ColumnIndexOutOfBounds: {
	index: number,
	len: number,
} }) & { Database?: never } | "PoolTimedOut" | "PoolClosed" | "WorkerCrashed" | "Other";

/**
 *  Tauri runtime errors. `Io`/`Json` are peeled off to the top-level `AppError`
 *  variants (same failure, one canonical code); everything else → `Other`.
 *  `tauri::Error` is `#[non_exhaustive]` and huge — only the codes we act on.
 */
export type TauriError = "InvalidArgs" | "Setup" | "Other";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

